language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: HEAqol5FFrpg+Ez132K9dY0gJSxxjaakdJGIYYcGAaq1bsR2Rd9HJEGSjEs/PniJI/xTZVuZHldSQZgHkgE4ELYc58DB+n3CILmcaDrjyIbLiBYipToj1Xc+Yg5lRG5iCfmFVcJiqN931Atn53BYIdokqdKC5ANDww4ajIzgZTkgrjSuzzKnVO66Oz4+cPL8GIBzfDKwEsMV7qAHhG0/ZwLP3qyKY14O/5aqskN50P739CFzSV8YNbh3bJxVjxDHvcSGNC03/KMMk2lyAliq9zMVUKkkbc9HpAVDbD5N/bFr2aDXzQLxyr6SDnEj0E7cxAr2OPJ3WCLxgQPnZXZrabLaSvXR21K3wHqCnjAfyjLcp8uoxBEhkHyPcQAcR9sOQc1l0YY9iaPwIXreBsBDsDfQtY0IVTX+xGpdQ6auffQ44FT8zRPfpDqh4oOdDJkobQIIgvGFNCcxmV8iN8YVo7G5Qho4blG1deC1vsTLkH4NfkRQc/uRobRk42xy3wrbdY7f5xiImeseSZPwMlCm3IhLj1OpaRHic2jtZaurfDhnC35EUr0/hWSu1Dx9AfRVfRaV+ireOmb44IJ3SlCaK23ohR9HCRhHmQXUS1odq7J/9lfz3Po8TgQfSB/YIpvog3GqILLXsi8NZpm9SHIPlac8fP/gbqFAveaXdSytqtg=
  app:
    master: warm-waters-98264
